# Stage 1: Build
FROM registry.access.redhat.com/ubi9/go-toolset:latest AS builder

USER root

WORKDIR /app

# Kopiera go.mod och go.sum
COPY go.mod ./

# Ladda ner dependencies
RUN go mod download

# Kopiera källkoden
COPY main.go ./

# Bygg applikationen
RUN go mod tidy && go build -o guestbook-api .

# Stage 2: Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

WORKDIR /app

# Kopiera den kompilerade binären från builder
COPY --from=builder /app/guestbook-api .

# Exponera port
EXPOSE 8080

# Kör applikationen
CMD ["./guestbook-api"]